export const modelSchemas = {
  PublicPage: {
    routeKey: "string",
    title: "string",
    slug: "string",
    heroHeading: "string",
    heroSubtitle: "string",
    bodySections: "array",
    imageUrls: "array",
    ctaText: "string",
    ctaLink: "string",
    seoTitle: "string",
    seoDescription: "string",
    ogImage: "string",
    status: "draft|published|archived",
  },
  CountryPage: {
    countryName: "string",
    slug: "string",
    heroImage: "string",
    overview: "string",
    benefits: "array",
    studyAreas: "array",
    intakes: "array|string",
    costGuide: "string",
    requirements: "array",
    visaNotes: "string",
    faqs: "array",
    seoTitle: "string",
    seoDescription: "string",
    status: "draft|published|archived",
  },
  Blog: {
    title: "string",
    slug: "string",
    excerpt: "string",
    content: "string|array",
    category: "string",
    tags: "array",
    featuredImage: "string",
    seoTitle: "string",
    metaDescription: "string",
    canonicalUrl: "string",
    status: "draft|published|archived",
    publishedAt: "date",
  },
  Lead: {
    name: "string",
    email: "string",
    phone: "string",
    interestedCountry: "string",
    educationLevel: "string",
    budgetRange: "string",
    intake: "string",
    examStatus: "string",
    passportStatus: "string",
    visaRefusalStatus: "string",
    message: "string",
    source: "pathway-planner|contact",
    status: "new|contacted|qualified|closed|lost",
    adminNotes: "string",
    createdAt: "date",
  },
  Media: {
    title: "string",
    url: "string",
    publicId: "string",
    altText: "string",
    uploadedBy: "string",
    createdAt: "date",
  },
  Settings: {
    siteName: "string",
    siteLogoUrl: "string",
    footerLogoUrl: "string",
    faviconUrl: "string",
    contactInfo: "object",
    socialLinks: "object",
    defaultSeoTitle: "string",
    defaultSeoDescription: "string",
    defaultOgImage: "string",
  },
};

export const collections = ["pages", "countries", "blogs", "leads", "media", "settings"];
