const officialContact = {
  address: "260 Sareng Tower, Malibag, Dhaka-1217, Bangladesh",
  phones: ["01898801960", "01898801961", "01898801962"],
};

const countrySeeds = [
  {
    id: "new-zealand",
    countryName: "New Zealand",
    slug: "new-zealand",
    heroHeading: "Study in New Zealand",
    heroSubtitle: "Calm campuses, practical pathways, and careful visa planning.",
    heroImage: "/images/destination-new-zealand.png",
    overview: "New Zealand is a focused option for students who want quality education, supportive campuses, and a calm study environment.",
    benefits: ["Student-friendly campuses", "Practical study pathways", "Clear documentation planning"],
    studyAreas: ["Business", "Information Technology", "Health Sciences", "Hospitality", "Engineering"],
    intakes: "Common intakes include February and July, with selected programmes offering additional starts.",
    costGuide: "Plan for tuition, living costs, insurance, accommodation, and visa documentation funds.",
    requirements: ["Academic transcripts", "English readiness", "Statement of purpose", "Financial documents", "Passport"],
    visaNotes: "Abroadways helps students prepare a consistent file, organise evidence, and understand visa documentation steps.",
  },
  {
    id: "united-kingdom",
    countryName: "United Kingdom",
    slug: "united-kingdom",
    heroHeading: "Study in the United Kingdom",
    heroSubtitle: "Focused applications for globally respected UK study options.",
    heroImage: "/images/destination-uk.png",
    overview: "The United Kingdom offers wide course choice, strong academic reputation, and structured application timelines.",
    benefits: ["Wide course choice", "Recognised universities", "Strong application timelines"],
    studyAreas: ["Business", "Computer Science", "Law", "Engineering", "Public Health"],
    intakes: "September is the main intake. January and selected spring intakes are also available at many institutions.",
    costGuide: "Plan for tuition, living expenses, health surcharge, visa fees, accommodation, and initial settlement costs.",
    requirements: ["Academic documents", "English evidence", "Personal statement", "CAS requirements", "Financial evidence"],
    visaNotes: "We support students with document organisation, university follow-up, and visa-readiness checks.",
  },
  {
    id: "australia",
    countryName: "Australia",
    slug: "australia",
    heroHeading: "Study in Australia",
    heroSubtitle: "Modern campuses with course planning built around your profile.",
    heroImage: "/images/destination-australia.png",
    overview: "Australia is a popular choice for students seeking modern campuses, diverse programmes, and structured planning.",
    benefits: ["Modern learning environment", "Diverse programmes", "Profile-led course selection"],
    studyAreas: ["Business", "IT", "Engineering", "Nursing", "Accounting"],
    intakes: "February and July are common intakes. Some institutions also offer trimester or rolling options.",
    costGuide: "Students should plan tuition, living costs, health cover, travel, accommodation, and visa documentation funds.",
    requirements: ["Academic transcripts", "English readiness", "Genuine study plan", "Financial documents", "Passport"],
    visaNotes: "Abroadways helps students prepare documents, review consistency, and plan the visa preparation timeline.",
  },
  {
    id: "canada",
    countryName: "Canada",
    slug: "canada",
    heroHeading: "Study in Canada",
    heroSubtitle: "Structured planning for competitive study applications.",
    heroImage: "/images/destination-canada.png",
    overview: "Canada requires careful planning around programme fit, budget, documentation, and application timing.",
    benefits: ["Competitive study options", "Profile-based planning", "Clear document strategy"],
    studyAreas: ["Business", "Computer Science", "Health", "Engineering", "Applied Sciences"],
    intakes: "Fall is the major intake. Winter and selected spring or summer intakes vary by institution and programme.",
    costGuide: "Plan tuition, living costs, proof of funds, travel, accommodation, and settlement expenses.",
    requirements: ["Academic records", "English readiness", "Study plan", "Financial evidence", "Passport"],
    visaNotes: "We help students organise documents and understand how to present a complete study plan.",
  },
  {
    id: "malaysia",
    countryName: "Malaysia",
    slug: "malaysia",
    heroHeading: "Study in Malaysia",
    heroSubtitle: "Accessible international education options with clear guidance.",
    heroImage: "/images/destination-malaysia.png",
    overview: "Malaysia offers accessible study options for students seeking international education close to home.",
    benefits: ["Accessible destination", "Practical budgets", "Fast planning options"],
    studyAreas: ["Business", "IT", "Hospitality", "Engineering", "Health Sciences"],
    intakes: "Multiple intakes are available depending on institution and programme, often with flexible start dates.",
    costGuide: "Plan tuition, living expenses, accommodation, medical insurance, travel, and documentation costs.",
    requirements: ["Academic documents", "Passport", "Application forms", "Financial planning", "Health documentation"],
    visaNotes: "Abroadways guides students through application and visa documentation preparation.",
  },
].map((country) => ({
  ...country,
  ctaText: "Start Pathway Planner",
  ctaLink: "/pathway-planner",
  seoTitle: `${country.heroHeading} | Abroadways`,
  seoDescription: `${country.heroSubtitle} Abroadways supports counselling, applications, visa guidance, and pre-departure planning.`,
  ogImage: country.heroImage,
  status: "published",
  faqs: [
    ["Can Abroadways help me choose a suitable course?", "Yes, counselling starts with your academic profile, budget, goals, and preferred intake."],
    ["Does Abroadways support visa documentation?", "Yes, we guide students on organising a consistent and complete visa-ready file."],
  ],
}));

export const seedData = {
  pages: [
    {
      id: "home",
      routeKey: "home",
      title: "Homepage",
      slug: "/",
      heroHeading: "Study Abroad with Confidence",
      heroSubtitle: "Clear counselling, university application, and visa guidance for Bangladeshi students.",
      imageUrls: ["/images/abroadways-hero-campus.png"],
      ctaTitle: "Start your study abroad journey today.",
      ctaText: "Book Free Consultation",
      ctaButtonText: "Book Free Consultation",
      ctaButtonLink: "/pathway-planner",
      bodySections: [
        { key: "hero", heading: "Study Abroad with Confidence", imageUrl: "/images/abroadways-hero-campus.png" },
        { key: "destination-cards", heading: "Focused destinations", imageUrl: "/images/abroadways-destination-planning.png" },
        { key: "services", heading: "Premium support without the noise", imageUrl: "/images/consultation-counsellor.png" },
        { key: "process", heading: "A structured journey from profile to departure", imageUrl: "/images/abroadways-destination-planning.png" },
        { key: "trust", heading: "Built around clarity and responsible guidance" },
        { key: "consultation-cta", heading: "Talk to an Abroadways counsellor", imageUrl: "/images/consultation-counsellor.png" },
        { key: "final-cta", heading: "Ready to plan your study abroad journey?" },
      ],
      seoTitle: "Abroadways | Study Abroad with Confidence",
      seoDescription: "Study abroad counselling for New Zealand, United Kingdom, Australia, Canada, and Malaysia.",
      ogImage: "/images/abroadways-hero-campus.png",
      status: "published",
    },
    {
      id: "study-abroad",
      routeKey: "study-abroad",
      title: "Study Abroad",
      slug: "/study-abroad",
      heroHeading: "Five destinations. One focused agency.",
      heroSubtitle: "Explore premium study pathways with Abroadways Limited.",
      imageUrls: ["/images/abroadways-hero-campus.png"],
      seoTitle: "Study Abroad Destinations | Abroadways",
      seoDescription: "Explore study abroad pathways for New Zealand, the United Kingdom, Australia, Canada, and Malaysia.",
      ogImage: "/images/abroadways-hero-campus.png",
      status: "published",
    },
    {
      id: "services",
      routeKey: "services",
      title: "Services",
      slug: "/services",
      heroHeading: "Counselling that makes the journey clear",
      heroSubtitle: "Practical support from country strategy to pre-departure.",
      imageUrls: ["/images/consultation-counsellor.png"],
      seoTitle: "Study Abroad Services | Abroadways",
      seoDescription: "Country selection, applications, budget guidance, visa documentation, and pre-departure support.",
      ogImage: "/images/consultation-counsellor.png",
      status: "published",
    },
    {
      id: "about-us",
      routeKey: "about-us",
      title: "About Us",
      slug: "/about-us",
      heroHeading: "A focused study abroad agency for Bangladeshi students",
      heroSubtitle: "Clear counselling and application guidance for selected destinations only.",
      imageUrls: ["/images/abroadways-hero-campus.png"],
      seoTitle: "About Abroadways Limited",
      seoDescription: "Abroadways Limited is a focused study abroad agency for Bangladeshi students.",
      ogImage: "/images/abroadways-hero-campus.png",
      status: "published",
    },
    {
      id: "contact",
      routeKey: "contact",
      title: "Contact",
      slug: "/contact",
      heroHeading: "Book your free consultation",
      heroSubtitle: "Visit or contact Abroadways for country planning, applications, and visa preparation.",
      imageUrls: ["/images/consultation-counsellor.png"],
      seoTitle: "Contact Abroadways",
      seoDescription: "Contact Abroadways Limited in Dhaka for study abroad counselling.",
      ogImage: "/images/consultation-counsellor.png",
      status: "published",
    },
  ],
  countries: countrySeeds,
  blogs: [
    {
      id: "choose-right-study-abroad-destination",
      title: "How to Choose the Right Study Abroad Destination",
      slug: "choose-right-study-abroad-destination",
      excerpt: "A practical guide for Bangladeshi students comparing country fit, budget, course goals, and documentation.",
      content: "Choosing a destination should begin with your academic background, preferred subject area, budget range, and long-term goals.\n\nA strong plan compares country fit, course quality, application timeline, documentation readiness, and family budget.",
      category: "Planning",
      tags: ["study abroad", "counselling"],
      featuredImage: "/images/abroadways-destination-planning.png",
      seoTitle: "How to Choose a Study Abroad Destination | Abroadways",
      metaDescription: "Compare country fit, budget, course goals, and documentation before choosing a study abroad destination.",
      status: "published",
      publishedAt: "2026-06-01",
    },
    {
      id: "prepare-before-university-application",
      title: "What to Prepare Before a University Application",
      slug: "prepare-before-university-application",
      excerpt: "Keep documents, timelines, intake choices, and budget evidence organised before you start applying.",
      content: "A complete application file usually starts with academic transcripts, certificates, passport, English readiness, and a clear study goal.\n\nStudents should also understand intake deadlines, budget requirements, and document consistency before submitting applications.",
      category: "Applications",
      tags: ["applications", "documents"],
      featuredImage: "/images/consultation-counsellor.png",
      seoTitle: "University Application Preparation | Abroadways",
      metaDescription: "A focused preparation guide for study abroad university applications.",
      status: "published",
      publishedAt: "2026-05-20",
    },
    {
      id: "budget-planning-for-study-abroad",
      title: "Budget Planning for Study Abroad",
      slug: "budget-planning-for-study-abroad",
      excerpt: "Tuition is only one part of the plan. Living costs, travel, visa fees, and settlement costs matter too.",
      content: "Good budget planning includes tuition, living costs, accommodation, insurance, visa costs, travel, and emergency funds.\n\nScholarships may help, but students should plan around realistic funding and transparent documentation.",
      category: "Budget",
      tags: ["budget", "scholarships"],
      featuredImage: "/images/destination-canada.png",
      seoTitle: "Budget Planning for Study Abroad | Abroadways",
      metaDescription: "Plan tuition, living costs, visa fees, travel, and settlement costs before studying abroad.",
      status: "published",
      publishedAt: "2026-05-08",
    },
  ],
  leads: [],
  media: [
    { id: "hero-campus", title: "Hero campus", url: "/images/abroadways-hero-campus.png", publicId: "hero-campus", altText: "Students on campus", uploadedBy: "system", createdAt: "2026-06-08T00:00:00.000Z" },
    { id: "consultation-counsellor", title: "Consultation counsellor", url: "/images/consultation-counsellor.png", publicId: "consultation-counsellor", altText: "Study abroad counselling session", uploadedBy: "system", createdAt: "2026-06-08T00:00:00.000Z" },
    { id: "destination-planning", title: "Destination planning", url: "/images/abroadways-destination-planning.png", publicId: "destination-planning", altText: "Study abroad planning materials", uploadedBy: "system", createdAt: "2026-06-08T00:00:00.000Z" },
  ],
  settings: [
    {
      id: "site",
      siteName: "Abroadways",
      siteLogoUrl: "",
      footerLogoUrl: "",
      faviconUrl: "",
      contactInfo: officialContact,
      socialLinks: {
        facebook: "https://www.facebook.com/abroadways",
        instagram: "https://instagram.com/abroadwaysbd",
      },
      defaultSeoTitle: "Abroadways | Study Abroad with Confidence",
      defaultSeoDescription: "Study abroad counselling for New Zealand, United Kingdom, Australia, Canada, and Malaysia.",
      defaultOgImage: "/images/abroadways-hero-campus.png",
      status: "published",
    },
  ],
};
