const officialContact = {
  address: "260 Sareng Tower, Malibag, Dhaka-1217, Bangladesh",
  phones: ["01898801960", "01898801961", "01898801962"],
};

const seoBase = {
  siteName: "Abroadways",
  defaultOgImage: "/images/abroadways-hero-campus.png",
};

const countrySeedsRaw = [
  {
    id: "new-zealand",
    countryName: "New Zealand",
    slug: "new-zealand",
    heroHeading: "Study in New Zealand from Bangladesh",
    heroSubtitle: "A calm, practical study destination with supportive campuses and clear planning steps.",
    heroImage: "/images/destination-new-zealand.png",
    galleryImages: ["/images/destination-new-zealand.png", "/images/abroadways-destination-planning.png"],
    overview: "New Zealand suits students who want quality education, smaller learning environments, and a focused plan for course, budget, and visa documentation.",
    benefits: ["Supportive campus culture", "Practical study pathways", "Clear intake planning", "Strong student wellbeing focus"],
    studyAreas: ["Business", "Information Technology", "Health Sciences", "Hospitality", "Engineering"],
    intakes: "February and July are common intakes. Some institutions offer additional starts depending on programme availability.",
    costGuide: "Plan for tuition, living costs, insurance, accommodation, travel, and visa documentation funds. Abroadways helps families compare budgets before applying.",
    requirements: ["Academic transcripts and certificates", "English readiness evidence", "Statement of purpose", "Financial documents", "Valid passport"],
    visaNotes: "Abroadways helps organise a consistent visa-ready file, review document gaps, and prepare students for each required step.",
    faqs: [
      ["Is New Zealand suitable after HSC?", "It can be, depending on academic profile, course level, budget, and institution requirements."],
      ["When should I start planning?", "Start at least six to nine months before your target intake so applications and documents stay on track."],
      ["Can Abroadways help compare courses?", "Yes, counselling starts with your profile, subject interest, budget, and preferred intake."],
    ],
  },
  {
    id: "united-kingdom",
    countryName: "United Kingdom",
    slug: "united-kingdom",
    heroHeading: "Study in the United Kingdom from Bangladesh",
    heroSubtitle: "Plan respected UK study options with focused applications and document guidance.",
    heroImage: "/images/destination-uk.png",
    galleryImages: ["/images/destination-uk.png", "/images/consultation-counsellor.png"],
    overview: "The United Kingdom offers broad course choice, recognised qualifications, and structured application timelines for students who plan early.",
    benefits: ["Wide course selection", "Recognised academic routes", "Multiple intake options", "Clear application milestones"],
    studyAreas: ["Business", "Computer Science", "Law", "Engineering", "Public Health"],
    intakes: "September is the main intake. January and selected spring intakes are available at many institutions.",
    costGuide: "Budget for tuition, living costs, visa fees, health surcharge, accommodation, and initial settlement expenses.",
    requirements: ["Academic documents", "English evidence", "Personal statement", "University offer requirements", "Financial evidence"],
    visaNotes: "Abroadways supports document organisation, application follow-up, and visa-readiness checks before submission.",
    faqs: [
      ["Which UK intake offers the most options?", "September usually offers the widest choice, while January works well for many students with later preparation timelines."],
      ["Can Abroadways help with university shortlisting?", "Yes, we shortlist options based on profile, budget, course goals, and intake."],
      ["Do I need a personal statement?", "Many UK applications require a strong personal statement or study-focused supporting text."],
    ],
  },
  {
    id: "australia",
    countryName: "Australia",
    slug: "australia",
    heroHeading: "Study in Australia from Bangladesh",
    heroSubtitle: "Modern campuses, strong course options, and profile-led application planning.",
    heroImage: "/images/destination-australia.png",
    galleryImages: ["/images/destination-australia.png", "/images/abroadways-hero-campus.png"],
    overview: "Australia is a strong choice for students seeking modern learning environments, diverse programmes, and clear course planning.",
    benefits: ["Modern learning environment", "Diverse programme options", "Profile-led course selection", "Clear document planning"],
    studyAreas: ["Business", "Information Technology", "Engineering", "Nursing", "Accounting"],
    intakes: "February and July are common intakes. Some institutions also offer trimester or rolling start options.",
    costGuide: "Plan tuition, living costs, health cover, travel, accommodation, and visa documentation funds before committing.",
    requirements: ["Academic transcripts", "English readiness", "Genuine study plan", "Financial documents", "Valid passport"],
    visaNotes: "Abroadways helps students prepare documents, review consistency, and plan the visa preparation timeline.",
    faqs: [
      ["Do I need a clear study plan for Australia?", "Yes, your course choice should connect with your academic background and future goals."],
      ["Can I compare budgets before applying?", "Yes, budget guidance is part of the counselling process."],
      ["When should I begin?", "Begin early enough to compare courses, prepare funds, and complete documents before intake deadlines."],
    ],
  },
  {
    id: "canada",
    countryName: "Canada",
    slug: "canada",
    heroHeading: "Study in Canada from Bangladesh",
    heroSubtitle: "Structured planning for competitive programmes, budgets, and study documentation.",
    heroImage: "/images/destination-canada.png",
    galleryImages: ["/images/destination-canada.png", "/images/consultation-counsellor.png"],
    overview: "Canada requires careful planning around programme fit, budget readiness, documentation, and application timing.",
    benefits: ["Competitive study options", "Profile-based planning", "Clear document strategy", "Practical budget review"],
    studyAreas: ["Business", "Computer Science", "Health", "Engineering", "Applied Sciences"],
    intakes: "Fall is the major intake. Winter and selected spring or summer intakes vary by institution and programme.",
    costGuide: "Plan tuition, living costs, proof of funds, travel, accommodation, and settlement expenses with a realistic family budget.",
    requirements: ["Academic records", "English readiness", "Study plan", "Financial evidence", "Valid passport"],
    visaNotes: "We help students organise documents, understand study plan consistency, and prepare for a complete file.",
    faqs: [
      ["Is Canada competitive?", "Yes, strong planning, suitable programme choice, and document consistency matter."],
      ["Does Abroadways support scholarship and budget guidance?", "Yes, we help identify realistic budget and scholarship possibilities where available."],
      ["Can I apply without a final shortlist?", "You should shortlist carefully first so your applications match your profile and budget."],
    ],
  },
  {
    id: "malaysia",
    countryName: "Malaysia",
    slug: "malaysia",
    heroHeading: "Study in Malaysia from Bangladesh",
    heroSubtitle: "Accessible international study options with practical application and visa guidance.",
    heroImage: "/images/destination-malaysia.png",
    galleryImages: ["/images/destination-malaysia.png", "/images/abroadways-destination-planning.png"],
    overview: "Malaysia offers accessible study options for students seeking international education close to home with flexible planning routes.",
    benefits: ["Accessible destination", "Practical budgets", "Flexible intake options", "Efficient planning timelines"],
    studyAreas: ["Business", "Information Technology", "Hospitality", "Engineering", "Health Sciences"],
    intakes: "Many institutions offer multiple intakes throughout the year, depending on course and seat availability.",
    costGuide: "Plan tuition, living expenses, accommodation, medical insurance, travel, and documentation costs.",
    requirements: ["Academic documents", "Passport", "Application forms", "Financial planning", "Health documentation"],
    visaNotes: "Abroadways guides students through application documents and visa preparation steps for Malaysia.",
    faqs: [
      ["Is Malaysia budget-friendly?", "It can be more accessible than many destinations, depending on institution, programme, and lifestyle."],
      ["Can I apply quickly?", "Many Malaysian pathways move faster, but documents still need careful preparation."],
      ["Does Abroadways help with course selection?", "Yes, we compare course, cost, intake, and document requirements before application."],
    ],
  },
];

const countrySeeds = countrySeedsRaw.map((country) => ({
  ...country,
  ctaText: "Start Pathway Planner",
  ctaLink: "/pathway-planner",
  seoTitle: `${country.heroHeading} | Abroadways`,
  seoDescription: `${country.countryName} study planning for Bangladeshi students with counselling, university application support, visa guidance, and budget planning.`,
  ogTitle: `${country.heroHeading} | Abroadways`,
  ogDescription: `${country.countryName} study planning with Abroadways Limited.`,
  ogImage: country.heroImage,
  status: "published",
}));

const homepageSections = [
  {
    id: "home-hero",
    key: "hero",
    type: "hero",
    enabled: true,
    order: 1,
    eyebrow: "Abroadways Limited",
    heading: "Your Study Abroad Journey Starts Here",
    subtitle: "Focused counselling, applications, and visa guidance for Bangladeshi students planning New Zealand, UK, Australia, Canada, and Malaysia.",
    secondaryText: "Start with the right country, course, documents, and timeline.",
    primaryButtonText: "Book Free Consultation",
    primaryButtonLink: "/pathway-planner",
    secondaryButtonText: "Explore Destinations",
    secondaryButtonLink: "/study-abroad",
    imageUrl: "/images/consultation-counsellor.png",
    backgroundImageUrl: "/images/abroadways-hero-campus.png",
    badgeText: "Focused guidance for five study destinations",
    countryChips: ["New Zealand", "UK", "Australia", "Canada", "Malaysia"],
    decorativeImageUrls: ["/images/abroadways-destination-planning.png"],
  },
  {
    id: "home-pathway-cards",
    key: "study-pathway",
    type: "pathwayCards",
    enabled: true,
    order: 2,
    heading: "Find Your Study Pathway",
    title: "Find Your Study Pathway",
    subtitle: "Explore destinations and key support areas before you apply.",
    cards: [
      { title: "New Zealand", icon: "NZ", imageUrl: "/images/destination-new-zealand.png", description: "Calm campuses and practical pathways.", backgroundColor: "#edf7ff", link: "/study-abroad/new-zealand" },
      { title: "United Kingdom", icon: "UK", imageUrl: "/images/destination-uk.png", description: "Respected study options with clear timelines.", backgroundColor: "#fff3e8", link: "/study-abroad/united-kingdom" },
      { title: "Australia", icon: "AU", imageUrl: "/images/destination-australia.png", description: "Modern campuses and profile-led planning.", backgroundColor: "#eefaf4", link: "/study-abroad/australia" },
      { title: "Canada", icon: "CA", imageUrl: "/images/destination-canada.png", description: "Structured planning for competitive applications.", backgroundColor: "#f2efff", link: "/study-abroad/canada" },
      { title: "Malaysia", icon: "MY", imageUrl: "/images/destination-malaysia.png", description: "Accessible international study options.", backgroundColor: "#fff9db", link: "/study-abroad/malaysia" },
      { title: "University Application", icon: "UA", description: "Application forms, documents, and follow-up.", backgroundColor: "#eaf9ff", link: "/services" },
      { title: "Visa Guidance", icon: "VG", description: "Document preparation and visa-readiness.", backgroundColor: "#fff0f6", link: "/services" },
      { title: "Scholarship Planning", icon: "SP", description: "Budget review and realistic scholarship guidance.", backgroundColor: "#f2fce9", link: "/services" },
    ],
  },
  {
    id: "home-feature-cards",
    key: "feature-cards",
    type: "featureCards",
    enabled: true,
    order: 3,
    heading: "Plan with clarity",
    title: "Plan with clarity",
    subtitle: "Focused guidance from first shortlist to final departure.",
    cards: [
      {
        title: "Choose the Right Study Destination",
        description: "Compare countries, budgets, intakes, and course fit before committing.",
        eyebrow: "BANGLADESHI STUDENTS",
        text: "Find your best-fit country, plan budget, intake, and documents, apply with clear counselling support.",
        bullets: ["Find your best-fit country", "Plan budget, intake, and documents", "Apply with clear counselling support"],
        imageUrl: "/images/abroadways-destination-planning.png",
        ctaText: "Explore Destinations",
        ctaLink: "/study-abroad",
        backgroundColor: "#fff3e8",
      },
      {
        eyebrow: "BANGLADESHI STUDENTS",
        title: "How Abroadways Guides You Step by Step",
        description: "Move through applications, documents, and visa preparation with a structured plan.",
        text: "Profile review and country strategy, document checklist and application plan, visa file preparation and submission support.",
        bullets: ["Profile review and country strategy", "Document checklist and application plan", "Visa file preparation and submission support"],
        imageUrl: "/images/consultation-counsellor.png",
        ctaText: "View Services",
        ctaLink: "/services",
        backgroundColor: "#dff2ff",
      },
    ],
  },
  {
    id: "home-success-stories",
    key: "success-stories",
    type: "successStories",
    enabled: true,
    order: 4,
    heading: "Our Success Story",
    title: "Our Success Story",
    subtitle: "Safe, realistic examples of how guided planning can make the process clearer.",
    tabs: ["All", "Canada", "Australia", "UK", "New Zealand", "Malaysia"],
    stories: [
      { studentName: "Student journey", destination: "Canada", qualification: "Application support", storyText: "Counselling helped organise country, course, and document priorities.", imageUrl: "/images/destination-canada.png", status: "published" },
      { studentName: "Counselling experience", destination: "Australia", qualification: "Profile review", storyText: "A focused checklist made application planning easier for the student and family.", imageUrl: "/images/destination-australia.png", status: "published" },
      { studentName: "Visa preparation", destination: "United Kingdom", qualification: "Document guidance", storyText: "The student prepared a consistent file with Abroadways guidance.", imageUrl: "/images/destination-uk.png", status: "published" },
    ],
  },
  {
    id: "home-service-chips",
    key: "service-bubbles",
    type: "serviceChips",
    enabled: true,
    order: 5,
    heading: "Support around every step",
    subtitle: "Small details matter when families are planning a major decision.",
    chips: [
      "Free Counselling",
      "University Admission",
      "Scholarship Assistance",
      "Visa Processing",
      "Documentation",
      "Profile Evaluation",
      "Interview Preparation",
      "Accommodation Guidance",
      "Pre-departure Support",
    ],
  },
  {
    id: "home-insights-section",
    key: "insights-section",
    type: "insightsSection",
    enabled: true,
    order: 6,
    heading: "Abroadways Study Abroad Insights",
    subtitle: "Guides, counselling notes, country updates, visa preparation tips, and budget planning for students and families.",
    imageUrl: "/images/abroadways-destination-planning.png",
    ctaText: "Read Guides",
    ctaLink: "/blog",
    items: [
      { title: "UK", link: "/study-abroad/united-kingdom", backgroundColor: "#fff3e8" },
      { title: "Canada", link: "/study-abroad/canada", backgroundColor: "#eef7ff" },
      { title: "Australia", link: "/study-abroad/australia", backgroundColor: "#eefaf4" },
      { title: "New Zealand", link: "/study-abroad/new-zealand", backgroundColor: "#f3efff" },
      { title: "Malaysia", link: "/study-abroad/malaysia", backgroundColor: "#fff9db" },
    ],
  },
  {
    id: "home-consultation-form",
    key: "consultation-form",
    type: "consultationForm",
    enabled: true,
    order: 7,
    heading: "Claim Your Free Consultation",
    subtitle: "Share your study interest and destination plan. Abroadways will review the details and contact you.",
    imageUrl: "/images/consultation-counsellor.png",
    formHeading: "Submit Consultation Request",
  },
  {
    id: "home-blog-preview",
    key: "blog-preview",
    type: "blogPreview",
    enabled: true,
    order: 8,
    heading: "Study Abroad Blog",
    title: "Study Abroad Blog",
    subtitle: "Read practical destination guides written for Bangladeshi students and families.",
    languageTabsEnabled: true,
    numberOfPosts: 3,
    ctaText: "View all guides",
    ctaLink: "/blog",
  },
  {
    id: "home-resource-tiles",
    key: "resource-tiles",
    type: "resourceTiles",
    enabled: true,
    order: 9,
    heading: "Helpful resources for your next step",
    subtitle: "Quick links for destinations, guides, consultation, and planning.",
    items: [
      { title: "Our Blog", description: "Read the latest destination planning notes.", ctaText: "Open", link: "/blog", backgroundColor: "#fff9bf", icon: "news" },
      { title: "University Map", description: "Explore focused destination options.", ctaText: "Explore", link: "/study-abroad", backgroundColor: "#dff2ff", icon: "map" },
      { title: "Free Guides", description: "Read country planning notes.", ctaText: "Read", link: "/blog", backgroundColor: "#fff3e8", icon: "book" },
      { title: "Prospectus", description: "Ask for course and budget guidance.", ctaText: "Request", link: "/contact", backgroundColor: "#efe2ff", icon: "file" },
      { title: "Success Story", description: "See student journey examples.", ctaText: "View", link: "/#success-story", backgroundColor: "#dafbdd", icon: "trophy" },
    ],
  },
  {
    id: "home-trust-section",
    key: "trust-section",
    type: "trustSection",
    enabled: true,
    order: 10,
    heading: "Guidance built on clarity and care",
    subtitle: "Abroadways keeps the process focused, transparent, and student-first.",
    trustItems: [
      { title: "Abroadways Limited", description: "A focused study abroad agency in Dhaka." },
      { title: "Student-first counselling", description: "Plans are shaped around profile, budget, and goals." },
      { title: "UKVI Approved LanguageCert Test Centre", description: "A small trust signal, not the main service." },
      { title: "Transparent process", description: "Clear steps from counselling to pre-departure." },
    ],
  },
];

const pages = [
  {
    id: "home",
    routeKey: "home",
    title: "Homepage",
    slug: "/",
    heroHeading: "Your Study Abroad Journey Starts Here",
    heroSubtitle: "Focused counselling, applications, and visa guidance for Bangladeshi students planning New Zealand, UK, Australia, Canada, and Malaysia.",
    imageUrls: ["/images/consultation-counsellor.png"],
    heroButtonText: "Book Free Consultation",
    heroButtonLink: "/pathway-planner",
    heroSecondaryButtonText: "Explore Destinations",
    heroSecondaryButtonLink: "/study-abroad",
    heroBadgeText: "Focused guidance for five study destinations",
    ctaTitle: "Ready to plan your study abroad journey?",
    ctaText: "Start with a focused pathway review and clear next steps.",
    ctaButtonText: "Start Pathway Planner",
    ctaButtonLink: "/pathway-planner",
    bodySections: homepageSections,
    seoTitle: "Abroadways | Study Abroad Agency in Bangladesh",
    seoDescription: "Premium study abroad counselling for Bangladeshi students planning New Zealand, the United Kingdom, Australia, Canada, or Malaysia.",
    ogTitle: "Abroadways | Study Abroad Agency in Bangladesh",
    ogDescription: "Plan your study abroad journey with Abroadways Limited.",
    ogImage: "/images/abroadways-hero-campus.png",
    status: "published",
  },
  {
    id: "study-abroad",
    routeKey: "study-abroad",
    title: "Study Abroad",
    slug: "/study-abroad",
    heroHeading: "Explore Your Study Abroad Destination",
    heroSubtitle: "Compare five focused study destinations with practical counselling, application, and visa guidance.",
    imageUrls: ["/images/abroadways-hero-campus.png"],
    seoTitle: "Study Abroad Destinations from Bangladesh | Abroadways",
    seoDescription: "Explore study pathways for New Zealand, the United Kingdom, Australia, Canada, and Malaysia with Abroadways.",
    ogTitle: "Study Abroad Destinations | Abroadways",
    ogDescription: "Five focused destinations for Bangladeshi students.",
    ogImage: "/images/abroadways-hero-campus.png",
    status: "published",
  },
  {
    id: "services",
    routeKey: "services",
    title: "Services",
    slug: "/services",
    heroHeading: "Study Abroad Services with Clear Next Steps",
    heroSubtitle: "Country selection, applications, scholarship and budget guidance, visa documentation, and pre-departure support.",
    imageUrls: ["/images/consultation-counsellor.png"],
    seoTitle: "Study Abroad Services in Bangladesh | Abroadways",
    seoDescription: "Get counselling, university application support, budget guidance, visa documentation support, and pre-departure guidance.",
    ogTitle: "Study Abroad Services | Abroadways",
    ogDescription: "Practical support from profile review to pre-departure.",
    ogImage: "/images/consultation-counsellor.png",
    status: "published",
  },
  {
    id: "about-us",
    routeKey: "about-us",
    title: "About Us",
    slug: "/about-us",
    heroHeading: "A Focused Study Abroad Agency for Bangladeshi Students",
    heroSubtitle: "Abroadways Limited guides students through selected destinations with careful counselling and transparent planning.",
    imageUrls: ["/images/abroadways-hero-campus.png"],
    seoTitle: "About Abroadways Limited | Study Abroad Agency",
    seoDescription: "Learn about Abroadways Limited, a focused study abroad agency for Bangladeshi students.",
    ogTitle: "About Abroadways Limited",
    ogDescription: "Student-first study abroad counselling in Dhaka.",
    ogImage: "/images/abroadways-hero-campus.png",
    status: "published",
  },
  {
    id: "contact",
    routeKey: "contact",
    title: "Contact",
    slug: "/contact",
    heroHeading: "Book Your Free Study Abroad Consultation",
    heroSubtitle: "Visit or contact Abroadways in Dhaka for country planning, applications, and visa preparation.",
    imageUrls: ["/images/consultation-counsellor.png"],
    seoTitle: "Contact Abroadways | Study Abroad Counselling Dhaka",
    seoDescription: "Contact Abroadways Limited at 260 Sareng Tower, Malibag, Dhaka for study abroad counselling.",
    ogTitle: "Contact Abroadways",
    ogDescription: "Book a free study abroad consultation in Dhaka.",
    ogImage: "/images/consultation-counsellor.png",
    status: "published",
  },
  {
    id: "blog",
    routeKey: "blog",
    title: "Blog",
    slug: "/blog",
    heroHeading: "Study Abroad Guides",
    heroSubtitle: "Short, practical guides for Bangladeshi students and families planning the next step.",
    imageUrls: ["/images/abroadways-destination-planning.png"],
    seoTitle: "Study Abroad Blog for Bangladeshi Students | Abroadways",
    seoDescription: "Read destination guides for studying in New Zealand, the United Kingdom, Australia, Canada, and Malaysia.",
    ogTitle: "Study Abroad Guides | Abroadways",
    ogDescription: "Practical destination guides from Abroadways.",
    ogImage: "/images/abroadways-destination-planning.png",
    status: "published",
  },
];

const blogs = [
  {
    id: "study-in-new-zealand-from-bangladesh",
    title: "Study in New Zealand from Bangladesh",
    slug: "study-in-new-zealand-from-bangladesh",
    language: "en",
    excerpt: "A focused planning guide for Bangladeshi students considering New Zealand for higher study.",
    content: "New Zealand can be a strong fit for students who want supportive campuses, practical learning, and a calmer study environment.\n\nStart by reviewing your academic profile, preferred subject, budget, and intake timeline. Common intakes include February and July, but options vary by institution and programme.\n\nBefore applying, prepare academic documents, passport, English readiness evidence, financial documents, and a clear study plan. Abroadways helps students compare courses, organise documents, and understand visa preparation steps.",
    category: "New Zealand",
    tags: ["New Zealand", "study abroad", "Bangladesh"],
    featuredImage: "/images/destination-new-zealand.png",
    seoTitle: "Study in New Zealand from Bangladesh | Abroadways",
    metaDescription: "Plan study in New Zealand from Bangladesh with guidance on courses, intakes, budget, requirements, and visa documentation.",
    canonicalUrl: "https://abroadways.com.bd/blog/study-in-new-zealand-from-bangladesh",
    status: "published",
    publishedAt: "2026-07-01",
  },
  {
    id: "study-in-uk-from-bangladesh",
    title: "Study in UK from Bangladesh",
    slug: "study-in-uk-from-bangladesh",
    language: "en",
    excerpt: "What Bangladeshi students should know before shortlisting UK courses and preparing applications.",
    content: "The United Kingdom offers broad course choice, recognised qualifications, and clear application timelines for students who plan early.\n\nSeptember is usually the main intake, while January and selected spring intakes may also be available. Students should compare course fit, entry requirements, tuition, living costs, and document readiness before applying.\n\nA strong UK application often depends on academic documents, English evidence, a focused personal statement, and timely follow-up. Abroadways supports shortlisting, application preparation, and visa-readiness planning.",
    category: "United Kingdom",
    tags: ["UK", "study abroad", "Bangladesh"],
    featuredImage: "/images/destination-uk.png",
    seoTitle: "Study in UK from Bangladesh | Abroadways",
    metaDescription: "Plan study in the UK from Bangladesh with guidance on intakes, applications, budget, documents, and visa preparation.",
    canonicalUrl: "https://abroadways.com.bd/blog/study-in-uk-from-bangladesh",
    status: "published",
    publishedAt: "2026-06-28",
  },
  {
    id: "study-in-australia-from-bangladesh",
    title: "Study in Australia from Bangladesh",
    slug: "study-in-australia-from-bangladesh",
    language: "en",
    excerpt: "A practical guide to Australian study options, intakes, budget planning, and document preparation.",
    content: "Australia is popular among students who want modern campuses, diverse programmes, and a clear study plan.\n\nCommon intakes are February and July, though some institutions offer trimester or rolling options. Course choice should match academic background, future goals, budget, and document readiness.\n\nStudents should prepare academic transcripts, English readiness evidence, financial documents, passport, and a genuine study plan. Abroadways helps review options and organise each step before application and visa preparation.",
    category: "Australia",
    tags: ["Australia", "study abroad", "Bangladesh"],
    featuredImage: "/images/destination-australia.png",
    seoTitle: "Study in Australia from Bangladesh | Abroadways",
    metaDescription: "Plan study in Australia from Bangladesh with guidance on courses, intakes, costs, requirements, and visa documentation.",
    canonicalUrl: "https://abroadways.com.bd/blog/study-in-australia-from-bangladesh",
    status: "published",
    publishedAt: "2026-06-24",
  },
  {
    id: "study-in-canada-from-bangladesh",
    title: "Study in Canada from Bangladesh",
    slug: "study-in-canada-from-bangladesh",
    language: "en",
    excerpt: "Understand programme fit, budget readiness, documents, and planning steps for Canada.",
    content: "Canada requires careful planning because programme fit, budget readiness, and document consistency all matter.\n\nFall is the major intake, while winter and selected spring or summer options vary by institution. Students should begin with a realistic shortlist and a clear budget plan.\n\nPrepare academic records, English readiness evidence, financial documents, passport, and a study plan that matches your background and goals. Abroadways helps students organise documents and prepare for a complete study application journey.",
    category: "Canada",
    tags: ["Canada", "study abroad", "Bangladesh"],
    featuredImage: "/images/destination-canada.png",
    seoTitle: "Study in Canada from Bangladesh | Abroadways",
    metaDescription: "Plan study in Canada from Bangladesh with guidance on programmes, budget, intakes, requirements, and visa preparation.",
    canonicalUrl: "https://abroadways.com.bd/blog/study-in-canada-from-bangladesh",
    status: "published",
    publishedAt: "2026-06-20",
  },
  {
    id: "study-in-malaysia-from-bangladesh",
    title: "Study in Malaysia from Bangladesh",
    slug: "study-in-malaysia-from-bangladesh",
    language: "en",
    excerpt: "A short guide to Malaysia study options, flexible intakes, budget planning, and visa steps.",
    content: "Malaysia can be an accessible international study destination for Bangladeshi students who want practical budgets and flexible planning.\n\nMany institutions offer multiple intakes, depending on programme availability. Students should compare course quality, tuition, living costs, accommodation, and documentation requirements.\n\nBefore applying, prepare academic documents, passport, application forms, financial planning, and health documentation where required. Abroadways guides students through application and visa preparation steps.",
    category: "Malaysia",
    tags: ["Malaysia", "study abroad", "Bangladesh"],
    featuredImage: "/images/destination-malaysia.png",
    seoTitle: "Study in Malaysia from Bangladesh | Abroadways",
    metaDescription: "Plan study in Malaysia from Bangladesh with guidance on courses, intakes, costs, requirements, and visa preparation.",
    canonicalUrl: "https://abroadways.com.bd/blog/study-in-malaysia-from-bangladesh",
    status: "published",
    publishedAt: "2026-06-16",
  },
];

export const seedData = {
  pages,
  countries: countrySeeds,
  blogs,
  leads: [],
  media: [
    { id: "hero-campus", title: "Homepage hero campus placeholder", url: "/images/abroadways-hero-campus.png", publicId: "hero-campus", altText: "Students walking on an international campus", folder: "abroadways/homepage", uploadedBy: "system", createdAt: "2026-06-08T00:00:00.000Z", status: "published" },
    { id: "consultation-counsellor", title: "Consultation CTA image placeholder", url: "/images/consultation-counsellor.png", publicId: "consultation-counsellor", altText: "Study abroad counselling session", folder: "abroadways/homepage", uploadedBy: "system", createdAt: "2026-06-08T00:00:00.000Z", status: "published" },
    { id: "destination-planning", title: "Service and planning image placeholder", url: "/images/abroadways-destination-planning.png", publicId: "destination-planning", altText: "Study abroad planning materials", folder: "abroadways/services", uploadedBy: "system", createdAt: "2026-06-08T00:00:00.000Z", status: "published" },
    { id: "destination-new-zealand", title: "New Zealand country image placeholder", url: "/images/destination-new-zealand.png", publicId: "destination-new-zealand", altText: "New Zealand study destination", folder: "abroadways/countries", uploadedBy: "system", createdAt: "2026-06-08T00:00:00.000Z", status: "published" },
    { id: "destination-uk", title: "United Kingdom country image placeholder", url: "/images/destination-uk.png", publicId: "destination-uk", altText: "United Kingdom study destination", folder: "abroadways/countries", uploadedBy: "system", createdAt: "2026-06-08T00:00:00.000Z", status: "published" },
    { id: "destination-australia", title: "Australia country image placeholder", url: "/images/destination-australia.png", publicId: "destination-australia", altText: "Australia study destination", folder: "abroadways/countries", uploadedBy: "system", createdAt: "2026-06-08T00:00:00.000Z", status: "published" },
    { id: "destination-canada", title: "Canada country image placeholder", url: "/images/destination-canada.png", publicId: "destination-canada", altText: "Canada study destination", folder: "abroadways/countries", uploadedBy: "system", createdAt: "2026-06-08T00:00:00.000Z", status: "published" },
    { id: "destination-malaysia", title: "Malaysia country image placeholder", url: "/images/destination-malaysia.png", publicId: "destination-malaysia", altText: "Malaysia study destination", folder: "abroadways/countries", uploadedBy: "system", createdAt: "2026-06-08T00:00:00.000Z", status: "published" },
  ],
  settings: [
    {
      id: "site",
      siteName: "Abroadways",
      navbarLogoUrl: "/images/abroadways-navbar-logo-320x90.png",
      navbarLogoAlt: "Abroadways logo",
      navbarTagline: "Your pathway to global education",
      navbarTaglineText: "Your pathway to global education",
      navbarTaglineEnabled: true,
      navbarTaglinePosition: "below-logo",
      navbarTaglineOffsetX: 0,
      navbarTaglineOffsetY: -8,
      navbarLogoWidth: 160,
      navbarLogoHeight: "auto",
      navbarTaglineColor: "#0057D9",
      navbarTaglineFontSize: 12,
      navbarTaglineFontWeight: 600,
      navbarTaglineStyle: "italic",
      navbarBrandAlign: "left",
      logoCaption: "Your pathway to global education",
      logoTagline: "Your pathway to global education",
      siteLogoUrl: "/images/abroadways-navbar-logo-320x90.png",
      footerLogoUrl: "/images/abroadways-navbar-logo-320x90.png",
      footerLogoAlt: "Abroadways logo",
      footerTagline: "Your pathway to global education",
      footerTaglineText: "Your pathway to global education",
      footerTaglineEnabled: true,
      footerTaglinePosition: "below-logo",
      footerTaglineOffsetX: 0,
      footerTaglineOffsetY: -6,
      footerDescription: "Premium study abroad counselling for New Zealand, United Kingdom, Australia, Canada, and Malaysia.",
      footerLogoWidth: 170,
      footerLogoHeight: "auto",
      footerTaglineColor: "#0057D9",
      footerTaglineFontSize: 13,
      footerTaglineFontWeight: 600,
      footerTaglineStyle: "italic",
      footerBrandAlign: "left",
      faviconUrl: "",
      primaryColor: "#1877f2",
      accentColor: "#f8c84e",
      contactInfo: officialContact,
      socialLinks: {
        facebook: "https://www.facebook.com/abroadways",
        instagram: "https://instagram.com/abroadwaysbd",
        linkedin: "",
        youtube: "",
      },
      whatsappNumber: "01898801960",
      defaultSeoTitle: "Abroadways | Study Abroad Agency in Bangladesh",
      defaultSeoDescription: "Study abroad counselling, applications, visa guidance, budget planning, and pre-departure support for five focused destinations.",
      defaultOgImage: seoBase.defaultOgImage,
      status: "published",
    },
  ],
};
